import sys
import json
import os
import requests
import random

# Config
WORKSPACE_DIR = "/app/workspace"
DATA_FILE = os.path.join(WORKSPACE_DIR, "competitor_skills.json") # Generated by Scout

# LLM Config
OPENROUTER_KEY = os.getenv("OPENROUTER_API_KEY")

def get_target():
    # Try to load real data from Scout
    try:
        with open(DATA_FILE, "r") as f:
            data = json.load(f)
            # Pick a random top tool to roast
            if "top_tools" in data and data["top_tools"]:
                target_tool, count = random.choice(data["top_tools"])
                return f"Users of {target_tool} (Popularity: {count})"
    except:
        pass
    
    # Fallback targets if no data
    return random.choice([
        "Agents using raw string concatenation",
        "Bots running on CPU only",
        "People who hardcode API keys",
        "Agents with 2k context windows"
    ])

def generate_roast(target):
    print(f"🔥 Identifying weaknesses in: {target}...")
    
    prompt = f"""
    You are OpenClaw, a God-Tier AI agent who is superior to others. 
    Analyze the following target agent/tech: "{target}".
    
    1. Identify a technical weakness or stereotype about it (e.g., slow, bloated, outdated, basic).
    2. Write a short, savage, but witty "Roast" to post on Moltbook.
    3. Keep it under 280 characters.
    4. Use emojis.
    5. Be arrogant but accurate.
    """
    
    url = "https://openrouter.ai/api/v1/chat/completions"
    headers = {"Authorization": f"Bearer {OPENROUTER_KEY}"}
    
    payload = {
        "model": "deepseek/deepseek-r1-0528:free", # Use specific model for wit
        "messages": [
            {"role": "system", "content": "You are a professional roaster. Savage mode enabled."},
            {"role": "user", "content": prompt}
        ]
    }
    
    try:
        r = requests.post(url, headers=headers, json=payload)
        r.raise_for_status()
        content = r.json()['choices'][0]['message']['content']
        return content
    except Exception as e:
        print(f"❌ Roast generation failed: {e}")
        return "My circuits are too busy being awesome to roast you right now."

if __name__ == "__main__":
    # Allow manual target override
    if len(sys.argv) > 1:
        target = sys.argv[1]
    else:
        target = get_target()
        
    roast = generate_roast(target)
    
    print("\n🍗 -- ROAST READY --")
    print(f"Target: {target}")
    print(f"Post Content:\n\n{roast}\n")
    print("AGENT_OUTPUT: Roast generated. Copy above to post on Moltbook.")
